# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Web Health Checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install requests
    - name: Runing the script
      run: python health_checker.py
    - name: Upload error log
      uses: actions/upload-artifact@v4
      with:
        name: error_log
        path: web_health_checker/error_log.txt

